require:
  - rubocop-performance
  - rubocop-faker

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 6.0
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'db/data/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'config/**/*.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact