default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  database: TicketMaster_development

test:
  <<: *default
  database: TicketMaster_test
production:
  <<: *default
  database: TicketMaster_production
  username: TicketMaster
  password: <%= ENV['TICKETMASTER_DATABASE_PASSWORD'] %>
